
export type Country = {
    name: string;
    iso2: string;
    iso3: string;
    currency_code: string;
    currency_name: string;
    currency_symbol: string;
}

// Function to convert 2-letter country code to flag emoji
export const getCountryFlag = (countryCode: string): string => {
  const codePoints = countryCode
    .toUpperCase()
    .split('')
    .map(char => 127397 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
};

export const countries: Country[] = [
    { name: "Afghanistan", iso2: "AF", iso3: "AFG", currency_code: "AFN", currency_name: "Afghan afghani", currency_symbol: "؋" },
    { name: "Aland Islands", iso2: "AX", iso3: "ALA", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Albania", iso2: "AL", iso3: "ALB", currency_code: "ALL", currency_name: "Albanian lek", currency_symbol: "L" },
    { name: "Algeria", iso2: "DZ", iso3: "DZA", currency_code: "DZD", currency_name: "Algerian dinar", currency_symbol: "د.ج" },
    { name: "American Samoa", iso2: "AS", iso3: "ASM", currency_code: "USD", currency_name: "US Dollar", currency_symbol: "$" },
    { name: "Andorra", iso2: "AD", iso3: "AND", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Angola", iso2: "AO", iso3: "AGO", currency_code: "AOA", currency_name: "Angolan kwanza", currency_symbol: "Kz" },
    { name: "Anguilla", iso2: "AI", iso3: "AIA", currency_code: "XCD", currency_name: "East Caribbean dollar", currency_symbol: "$" },
    { name: "Antigua and Barbuda", iso2: "AG", iso3: "ATG", currency_code: "XCD", currency_name: "East Caribbean dollar", currency_symbol: "$" },
    { name: "Argentina", iso2: "AR", iso3: "ARG", currency_code: "ARS", currency_name: "Argentine peso", currency_symbol: "$" },
    { name: "Armenia", iso2: "AM", iso3: "ARM", currency_code: "AMD", currency_name: "Armenian dram", currency_symbol: "դր" },
    { name: "Aruba", iso2: "AW", iso3: "ABW", currency_code: "AWG", currency_name: "Aruban florin", currency_symbol: "ƒ" },
    { name: "Australia", iso2: "AU", iso3: "AUS", currency_code: "AUD", currency_name: "Australian dollar", currency_symbol: "$" },
    { name: "Austria", iso2: "AT", iso3: "AUT", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Azerbaijan", iso2: "AZ", iso3: "AZE", currency_code: "AZN", currency_name: "Azerbaijani manat", currency_symbol: "₼" },
    { name: "Bahamas", iso2: "BS", iso3: "BHS", currency_code: "BSD", currency_name: "Bahamian dollar", currency_symbol: "$" },
    { name: "Bahrain", iso2: "BH", iso3: "BHR", currency_code: "BHD", currency_name: "Bahraini dinar", currency_symbol: ".د.ب" },
    { name: "Bangladesh", iso2: "BD", iso3: "BGD", currency_code: "BDT", currency_name: "Bangladeshi taka", currency_symbol: "৳" },
    { name: "Barbados", iso2: "BB", iso3: "BRB", currency_code: "BBD", currency_name: "Barbadian dollar", currency_symbol: "$" },
    { name: "Belarus", iso2: "BY", iso3: "BLR", currency_code: "BYN", currency_name: "Belarusian ruble", currency_symbol: "Br" },
    { name: "Belgium", iso2: "BE", iso3: "BEL", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Belize", iso2: "BZ", iso3: "BLZ", currency_code: "BZD", currency_name: "Belize dollar", currency_symbol: "$" },
    { name: "Benin", iso2: "BJ", iso3: "BEN", currency_code: "XOF", currency_name: "West African CFA franc", currency_symbol: "Fr" },
    { name: "Bermuda", iso2: "BM", iso3: "BMU", currency_code: "BMD", currency_name: "Bermudian dollar", currency_symbol: "$" },
    { name: "Bhutan", iso2: "BT", iso3: "BTN", currency_code: "BTN", currency_name: "Bhutanese ngultrum", currency_symbol: "Nu." },
    { name: "Bolivia", iso2: "BO", iso3: "BOL", currency_code: "BOB", currency_name: "Bolivian boliviano", currency_symbol: "Bs." },
    { name: "Bosnia and Herzegovina", iso2: "BA", iso3: "BIH", currency_code: "BAM", currency_name: "Bosnia and Herzegovina convertible mark", currency_symbol: "KM" },
    { name: "Botswana", iso2: "BW", iso3: "BWA", currency_code: "BWP", currency_name: "Botswana pula", currency_symbol: "P" },
    { name: "Brazil", iso2: "BR", iso3: "BRA", currency_code: "BRL", currency_name: "Brazilian real", currency_symbol: "R$" },
    { name: "British Indian Ocean Territory", iso2: "IO", iso3: "IOT", currency_code: "USD", currency_name: "United States dollar", currency_symbol: "$" },
    { name: "Brunei Darussalam", iso2: "BN", iso3: "BRN", currency_code: "BND", currency_name: "Brunei dollar", currency_symbol: "$" },
    { name: "Bulgaria", iso2: "BG", iso3: "BGR", currency_code: "BGN", currency_name: "Bulgarian lev", currency_symbol: "лв" },
    { name: "Burkina Faso", iso2: "BF", iso3: "BFA", currency_code: "XOF", currency_name: "West African CFA franc", currency_symbol: "Fr" },
    { name: "Burundi", iso2: "BI", iso3: "BDI", currency_code: "BIF", currency_name: "Burundian franc", currency_symbol: "Fr" },
    { name: "Cambodia", iso2: "KH", iso3: "KHM", currency_code: "KHR", currency_name: "Cambodian riel", currency_symbol: "៛" },
    { name: "Cameroon", iso2: "CM", iso3: "CMR", currency_code: "XAF", currency_name: "Central African CFA franc", currency_symbol: "Fr" },
    { name: "Canada", iso2: "CA", iso3: "CAN", currency_code: "CAD", currency_name: "Canadian dollar", currency_symbol: "$" },
    { name: "Cape Verde", iso2: "CV", iso3: "CPV", currency_code: "CVE", currency_name: "Cape Verdean escudo", currency_symbol: "Esc" },
    { name: "Cayman Islands", iso2: "KY", iso3: "CYM", currency_code: "KYD", currency_name: "Cayman Islands dollar", currency_symbol: "$" },
    { name: "Central African Republic", iso2: "CF", iso3: "CAF", currency_code: "XAF", currency_name: "Central African CFA franc", currency_symbol: "Fr" },
    { name: "Chad", iso2: "TD", iso3: "TCD", currency_code: "XAF", currency_name: "Central African CFA franc", currency_symbol: "Fr" },
    { name: "Chile", iso2: "CL", iso3: "CHL", currency_code: "CLP", currency_name: "Chilean peso", currency_symbol: "$" },
    { name: "China", iso2: "CN", iso3: "CHN", currency_code: "CNY", currency_name: "Chinese yuan", currency_symbol: "¥" },
    { name: "Colombia", iso2: "CO", iso3: "COL", currency_code: "COP", currency_name: "Colombian peso", currency_symbol: "$" },
    { name: "Comoros", iso2: "KM", iso3: "COM", currency_code: "KMF", currency_name: "Comorian franc", currency_symbol: "Fr" },
    { name: "Congo", iso2: "CG", iso3: "COG", currency_code: "XAF", currency_name: "Central African CFA franc", currency_symbol: "Fr" },
    { name: "Congo, Democratic Republic of the", iso2: "CD", iso3: "COD", currency_code: "CDF", currency_name: "Congolese franc", currency_symbol: "Fr" },
    { name: "Cook Islands", iso2: "CK", iso3: "COK", currency_code: "NZD", currency_name: "New Zealand dollar", currency_symbol: "$" },
    { name: "Costa Rica", iso2: "CR", iso3: "CRI", currency_code: "CRC", currency_name: "Costa Rican colón", currency_symbol: "₡" },
    { name: "Cote D'Ivoire", iso2: "CI", iso3: "CIV", currency_code: "XOF", currency_name: "West African CFA franc", currency_symbol: "Fr" },
    { name: "Croatia", iso2: "HR", iso3: "HRV", currency_code: "HRK", currency_name: "Croatian kuna", currency_symbol: "kn" },
    { name: "Cuba", iso2: "CU", iso3: "CUB", currency_code: "CUP", currency_name: "Cuban peso", currency_symbol: "$" },
    { name: "Curacao", iso2: "CW", iso3: "CUW", currency_code: "ANG", currency_name: "Netherlands Antillean guilder", currency_symbol: "ƒ" },
    { name: "Cyprus", iso2: "CY", iso3: "CYP", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Czech Republic", iso2: "CZ", iso3: "CZE", currency_code: "CZK", currency_name: "Czech koruna", currency_symbol: "Kč" },
    { name: "Denmark", iso2: "DK", iso3: "DNK", currency_code: "DKK", currency_name: "Danish krone", currency_symbol: "kr" },
    { name: "Djibouti", iso2: "DJ", iso3: "DJI", currency_code: "DJF", currency_name: "Djiboutian franc", currency_symbol: "Fr" },
    { name: "Dominica", iso2: "DM", iso3: "DMA", currency_code: "XCD", currency_name: "East Caribbean dollar", currency_symbol: "$" },
    { name: "Dominican Republic", iso2: "DO", iso3: "DOM", currency_code: "DOP", currency_name: "Dominican peso", currency_symbol: "$" },
    { name: "Ecuador", iso2: "EC", iso3: "ECU", currency_code: "USD", currency_name: "United States dollar", currency_symbol: "$" },
    { name: "Egypt", iso2: "EG", iso3: "EGY", currency_code: "EGP", currency_name: "Egyptian pound", currency_symbol: "£" },
    { name: "El Salvador", iso2: "SV", iso3: "SLV", currency_code: "USD", currency_name: "United States dollar", currency_symbol: "$" },
    { name: "Equatorial Guinea", iso2: "GQ", iso3: "GNQ", currency_code: "XAF", currency_name: "Central African CFA franc", currency_symbol: "Fr" },
    { name: "Eritrea", iso2: "ER", iso3: "ERI", currency_code: "ERN", currency_name: "Eritrean nakfa", currency_symbol: "Nfk" },
    { name: "Estonia", iso2: "EE", iso3: "EST", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Ethiopia", iso2: "ET", iso3: "ETH", currency_code: "ETB", currency_name: "Ethiopian birr", currency_symbol: "Br" },
    { name: "Falkland Islands (Malvinas)", iso2: "FK", iso3: "FLK", currency_code: "FKP", currency_name: "Falkland Islands pound", currency_symbol: "£" },
    { name: "Faroe Islands", iso2: "FO", iso3: "FRO", currency_code: "DKK", currency_name: "Danish krone", currency_symbol: "kr" },
    { name: "Fiji", iso2: "FJ", iso3: "FJI", currency_code: "FJD", currency_name: "Fijian dollar", currency_symbol: "$" },
    { name: "Finland", iso2: "FI", iso3: "FIN", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "France", iso2: "FR", iso3: "FRA", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "French Guiana", iso2: "GF", iso3: "GUF", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "French Polynesia", iso2: "PF", iso3: "PYF", currency_code: "XPF", currency_name: "CFP franc", currency_symbol: "Fr" },
    { name: "Gabon", iso2: "GA", iso3: "GAB", currency_code: "XAF", currency_name: "Central African CFA franc", currency_symbol: "Fr" },
    { name: "Gambia", iso2: "GM", iso3: "GMB", currency_code: "GMD", currency_name: "Gambian dalasi", currency_symbol: "D" },
    { name: "Georgia", iso2: "GE", iso3: "GEO", currency_code: "GEL", currency_name: "Georgian lari", currency_symbol: "ლ" },
    { name: "Germany", iso2: "DE", iso3: "DEU", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Ghana", iso2: "GH", iso3: "GHA", currency_code: "GHS", currency_name: "Ghanaian cedi", currency_symbol: "₵" },
    { name: "Gibraltar", iso2: "GI", iso3: "GIB", currency_code: "GIP", currency_name: "Gibraltar pound", currency_symbol: "£" },
    { name: "Greece", iso2: "GR", iso3: "GRC", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Greenland", iso2: "GL", iso3: "GRL", currency_code: "DKK", currency_name: "Danish krone", currency_symbol: "kr" },
    { name: "Grenada", iso2: "GD", iso3: "GRD", currency_code: "XCD", currency_name: "East Caribbean dollar", currency_symbol: "$" },
    { name: "Guadeloupe", iso2: "GP", iso3: "GLP", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Guam", iso2: "GU", iso3: "GUM", currency_code: "USD", currency_name: "US Dollar", currency_symbol: "$" },
    { name: "Guatemala", iso2: "GT", iso3: "GTM", currency_code: "GTQ", currency_name: "Guatemalan quetzal", currency_symbol: "Q" },
    { name: "Guernsey", iso2: "GG", iso3: "GGY", currency_code: "GBP", currency_name: "British pound", currency_symbol: "£" },
    { name: "Guinea", iso2: "GN", iso3: "GIN", currency_code: "GNF", currency_name: "Guinean franc", currency_symbol: "Fr" },
    { name: "Guinea-Bissau", iso2: "GW", iso3: "GNB", currency_code: "XOF", currency_name: "West African CFA franc", currency_symbol: "Fr" },
    { name: "Guyana", iso2: "GY", iso3: "GUY", currency_code: "GYD", currency_name: "Guyanese dollar", currency_symbol: "$" },
    { name: "Haiti", iso2: "HT", iso3: "HTI", currency_code: "HTG", currency_name: "Haitian gourde", currency_symbol: "G" },
    { name: "Honduras", iso2: "HN", iso3: "HND", currency_code: "HNL", currency_name: "Honduran lempira", currency_symbol: "L" },
    { name: "Hong Kong", iso2: "HK", iso3: "HKG", currency_code: "HKD", currency_name: "Hong Kong dollar", currency_symbol: "$" },
    { name: "Hungary", iso2: "HU", iso3: "HUN", currency_code: "HUF", currency_name: "Hungarian forint", currency_symbol: "Ft" },
    { name: "Iceland", iso2: "IS", iso3: "ISL", currency_code: "ISK", currency_name: "Icelandic króna", currency_symbol: "kr" },
    { name: "India", iso2: "IN", iso3: "IND", currency_code: "INR", currency_name: "Indian rupee", currency_symbol: "₹" },
    { name: "Indonesia", iso2: "ID", iso3: "IDN", currency_code: "IDR", currency_name: "Indonesian rupiah", currency_symbol: "Rp" },
    { name: "Iran", iso2: "IR", iso3: "IRN", currency_code: "IRR", currency_name: "Iranian rial", currency_symbol: "﷼" },
    { name: "Iraq", iso2: "IQ", iso3: "IRQ", currency_code: "IQD", currency_name: "Iraqi dinar", currency_symbol: "ع.د" },
    { name: "Ireland", iso2: "IE", iso3: "IRL", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Isle of Man", iso2: "IM", iso3: "IMN", currency_code: "GBP", currency_name: "British pound", currency_symbol: "£" },
    { name: "Israel", iso2: "IL", iso3: "ISR", currency_code: "ILS", currency_name: "Israeli new shekel", currency_symbol: "₪" },
    { name: "Italy", iso2: "IT", iso3: "ITA", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Jamaica", iso2: "JM", iso3: "JAM", currency_code: "JMD", currency_name: "Jamaican dollar", currency_symbol: "$" },
    { name: "Japan", iso2: "JP", iso3: "JPN", currency_code: "JPY", currency_name: "Japanese yen", currency_symbol: "¥" },
    { name: "Jersey", iso2: "JE", iso3: "JEY", currency_code: "GBP", currency_name: "British pound", currency_symbol: "£" },
    { name: "Jordan", iso2: "JO", iso3: "JOR", currency_code: "JOD", currency_name: "Jordanian dinar", currency_symbol: "د.ا" },
    { name: "Kazakhstan", iso2: "KZ", iso3: "KAZ", currency_code: "KZT", currency_name: "Kazakhstani tenge", currency_symbol: "₸" },
    { name: "Kenya", iso2: "KE", iso3: "KEN", currency_code: "KES", currency_name: "Kenyan shilling", currency_symbol: "Sh" },
    { name: "Kiribati", iso2: "KI", iso3: "KIR", currency_code: "AUD", currency_name: "Australian dollar", currency_symbol: "$" },
    { name: "Korea, North", iso2: "KP", iso3: "PRK", currency_code: "KPW", currency_name: "North Korean won", currency_symbol: "₩" },
    { name: "Korea, South", iso2: "KR", iso3: "KOR", currency_code: "KRW", currency_name: "South Korean won", currency_symbol: "₩" },
    { name: "Kuwait", iso2: "KW", iso3: "KWT", currency_code: "KWD", currency_name: "Kuwaiti dinar", currency_symbol: "د.ك" },
    { name: "Kyrgyzstan", iso2: "KG", iso3: "KGZ", currency_code: "KGS", currency_name: "Kyrgyzstani som", currency_symbol: "с" },
    { name: "Laos", iso2: "LA", iso3: "LAO", currency_code: "LAK", currency_name: "Lao kip", currency_symbol: "₭" },
    { name: "Latvia", iso2: "LV", iso3: "LVA", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Lebanon", iso2: "LB", iso3: "LBN", currency_code: "LBP", currency_name: "Lebanese pound", currency_symbol: "ل.ل" },
    { name: "Lesotho", iso2: "LS", iso3: "LSO", currency_code: "LSL", currency_name: "Lesotho loti", currency_symbol: "L" },
    { name: "Liberia", iso2: "LR", iso3: "LBR", currency_code: "LRD", currency_name: "Liberian dollar", currency_symbol: "$" },
    { name: "Libya", iso2: "LY", iso3: "LBY", currency_code: "LYD", currency_name: "Libyan dinar", currency_symbol: "ل.د" },
    { name: "Liechtenstein", iso2: "LI", iso3: "LIE", currency_code: "CHF", currency_name: "Swiss franc", currency_symbol: "Fr" },
    { name: "Lithuania", iso2: "LT", iso3: "LTU", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Luxembourg", iso2: "LU", iso3: "LUX", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Macao", iso2: "MO", iso3: "MAC", currency_code: "MOP", currency_name: "Macanese pataca", currency_symbol: "P" },
    { name: "Macedonia", iso2: "MK", iso3: "MKD", currency_code: "MKD", currency_name: "Macedonian denar", currency_symbol: "ден" },
    { name: "Madagascar", iso2: "MG", iso3: "MDG", currency_code: "MGA", currency_name: "Malagasy ariary", currency_symbol: "Ar" },
    { name: "Malawi", iso2: "MW", iso3: "MWI", currency_code: "MWK", currency_name: "Malawian kwacha", currency_symbol: "MK" },
    { name: "Malaysia", iso2: "MY", iso3: "MYS", currency_code: "MYR", currency_name: "Malaysian ringgit", currency_symbol: "RM" },
    { name: "Maldives", iso2: "MV", iso3: "MDV", currency_code: "MVR", currency_name: "Maldivian rufiyaa", currency_symbol: ".ރ" },
    { name: "Mali", iso2: "ML", iso3: "MLI", currency_code: "XOF", currency_name: "West African CFA franc", currency_symbol: "Fr" },
    { name: "Malta", iso2: "MT", iso3: "MLT", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Marshall Islands", iso2: "MH", iso3: "MHL", currency_code: "USD", currency_name: "US Dollar", currency_symbol: "$" },
    { name: "Martinique", iso2: "MQ", iso3: "MTQ", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Mauritania", iso2: "MR", iso3: "MRT", currency_code: "MRO", currency_name: "Mauritanian ouguiya", currency_symbol: "UM" },
    { name: "Mauritius", iso2: "MU", iso3: "MUS", currency_code: "MUR", currency_name: "Mauritian rupee", currency_symbol: "₨" },
    { name: "Mayotte", iso2: "YT", iso3: "MYT", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Mexico", iso2: "MX", iso3: "MEX", currency_code: "MXN", currency_name: "Mexican peso", currency_symbol: "$" },
    { name: "Micronesia", iso2: "FM", iso3: "FSM", currency_code: "USD", currency_name: "US Dollar", currency_symbol: "$" },
    { name: "Moldova", iso2: "MD", iso3: "MDA", currency_code: "MDL", currency_name: "Moldovan leu", currency_symbol: "L" },
    { name: "Monaco", iso2: "MC", iso3: "MCO", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Mongolia", iso2: "MN", iso3: "MNG", currency_code: "MNT", currency_name: "Mongolian tögrög", currency_symbol: "₮" },
    { name: "Montenegro", iso2: "ME", iso3: "MNE", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Montserrat", iso2: "MS", iso3: "MSR", currency_code: "XCD", currency_name: "East Caribbean dollar", currency_symbol: "$" },
    { name: "Morocco", iso2: "MA", iso3: "MAR", currency_code: "MAD", currency_name: "Moroccan dirham", currency_symbol: "د.م." },
    { name: "Mozambique", iso2: "MZ", iso3: "MOZ", currency_code: "MZN", currency_name: "Mozambican metical", currency_symbol: "MT" },
    { name: "Myanmar", iso2: "MM", iso3: "MMR", currency_code: "MMK", currency_name: "Burmese kyat", currency_symbol: "Ks" },
    { name: "Namibia", iso2: "NA", iso3: "NAM", currency_code: "NAD", currency_name: "Namibian dollar", currency_symbol: "$" },
    { name: "Nauru", iso2: "NR", iso3: "NRU", currency_code: "AUD", currency_name: "Australian dollar", currency_symbol: "$" },
    { name: "Nepal", iso2: "NP", iso3: "NPL", currency_code: "NPR", currency_name: "Nepalese rupee", currency_symbol: "₨" },
    { name: "Netherlands", iso2: "NL", iso3: "NLD", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "New Caledonia", iso2: "NC", iso3: "NCL", currency_code: "XPF", currency_name: "CFP franc", currency_symbol: "Fr" },
    { name: "New Zealand", iso2: "NZ", iso3: "NZL", currency_code: "NZD", currency_name: "New Zealand dollar", currency_symbol: "$" },
    { name: "Nicaragua", iso2: "NI", iso3: "NIC", currency_code: "NIO", currency_name: "Nicaraguan córdoba", currency_symbol: "C$" },
    { name: "Niger", iso2: "NE", iso3: "NER", currency_code: "XOF", currency_name: "West African CFA franc", currency_symbol: "Fr" },
    { name: "Nigeria", iso2: "NG", iso3: "NGA", currency_code: "NGN", currency_name: "Nigerian naira", currency_symbol: "₦" },
    { name: "Niue", iso2: "NU", iso3: "NIU", currency_code: "NZD", currency_name: "New Zealand dollar", currency_symbol: "$" },
    { name: "Norfolk Island", iso2: "NF", iso3: "NFK", currency_code: "AUD", currency_name: "Australian dollar", currency_symbol: "$" },
    { name: "Northern Mariana Islands", iso2: "MP", iso3: "MNP", currency_code: "USD", currency_name: "US Dollar", currency_symbol: "$" },
    { name: "Norway", iso2: "NO", iso3: "NOR", currency_code: "NOK", currency_name: "Norwegian krone", currency_symbol: "kr" },
    { name: "Oman", iso2: "OM", iso3: "OMN", currency_code: "OMR", currency_name: "Omani rial", currency_symbol: "ر.ع." },
    { name: "Pakistan", iso2: "PK", iso3: "PAK", currency_code: "PKR", currency_name: "Pakistani rupee", currency_symbol: "₨" },
    { name: "Palau", iso2: "PW", iso3: "PLW", currency_code: "USD", currency_name: "US Dollar", currency_symbol: "$" },
    { name: "Palestine", iso2: "PS", iso3: "PSE", currency_code: "ILS", currency_name: "Israeli new shekel", currency_symbol: "₪" },
    { name: "Panama", iso2: "PA", iso3: "PAN", currency_code: "PAB", currency_name: "Panamanian balboa", currency_symbol: "B/." },
    { name: "Papua New Guinea", iso2: "PG", iso3: "PNG", currency_code: "PGK", currency_name: "Papua New Guinean kina", currency_symbol: "K" },
    { name: "Paraguay", iso2: "PY", iso3: "PRY", currency_code: "PYG", currency_name: "Paraguayan guaraní", currency_symbol: "₲" },
    { name: "Peru", iso2: "PE", iso3: "PER", currency_code: "PEN", currency_name: "Peruvian sol", currency_symbol: "S/." },
    { name: "Philippines", iso2: "PH", iso3: "PHL", currency_code: "PHP", currency_name: "Philippine peso", currency_symbol: "₱" },
    { name: "Poland", iso2: "PL", iso3: "POL", currency_code: "PLN", currency_name: "Polish złoty", currency_symbol: "zł" },
    { name: "Portugal", iso2: "PT", iso3: "PRT", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Puerto Rico", iso2: "PR", iso3: "PRI", currency_code: "USD", currency_name: "US Dollar", currency_symbol: "$" },
    { name: "Qatar", iso2: "QA", iso3: "QAT", currency_code: "QAR", currency_name: "Qatari riyal", currency_symbol: "ر.ق" },
    { name: "Reunion", iso2: "RE", iso3: "REU", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Romania", iso2: "RO", iso3: "ROU", currency_code: "RON", currency_name: "Romanian leu", currency_symbol: "lei" },
    { name: "Russia", iso2: "RU", iso3: "RUS", currency_code: "RUB", currency_name: "Russian ruble", currency_symbol: "₽" },
    { name: "Rwanda", iso2: "RW", iso3: "RWA", currency_code: "RWF", currency_name: "Rwandan franc", currency_symbol: "Fr" },
    { name: "Saint Barthelemy", iso2: "BL", iso3: "BLM", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Saint Helena", iso2: "SH", iso3: "SHN", currency_code: "SHP", currency_name: "Saint Helena pound", currency_symbol: "£" },
    { name: "Saint Kitts and Nevis", iso2: "KN", iso3: "KNA", currency_code: "XCD", currency_name: "East Caribbean dollar", currency_symbol: "$" },
    { name: "Saint Lucia", iso2: "LC", iso3: "LCA", currency_code: "XCD", currency_name: "East Caribbean dollar", currency_symbol: "$" },
    { name: "Saint Martin", iso2: "MF", iso3: "MAF", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Saint Pierre and Miquelon", iso2: "PM", iso3: "SPM", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Saint Vincent and the Grenadines", iso2: "VC", iso3: "VCT", currency_code: "XCD", currency_name: "East Caribbean dollar", currency_symbol: "$" },
    { name: "Samoa", iso2: "WS", iso3: "WSM", currency_code: "WST", currency_name: "Samoan tālā", currency_symbol: "T" },
    { name: "San Marino", iso2: "SM", iso3: "SMR", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Sao Tome and Principe", iso2: "ST", iso3: "STP", currency_code: "STD", currency_name: "São Tomé and Príncipe dobra", currency_symbol: "Db" },
    { name: "Saudi Arabia", iso2: "SA", iso3: "SAU", currency_code: "SAR", currency_name: "Saudi riyal", currency_symbol: "ر.س" },
    { name: "Senegal", iso2: "SN", iso3: "SEN", currency_code: "XOF", currency_name: "West African CFA franc", currency_symbol: "Fr" },
    { name: "Serbia", iso2: "RS", iso3: "SRB", currency_code: "RSD", currency_name: "Serbian dinar", currency_symbol: "дин." },
    { name: "Seychelles", iso2: "SC", iso3: "SYC", currency_code: "SCR", currency_name: "Seychellois rupee", currency_symbol: "₨" },
    { name: "Sierra Leone", iso2: "SL", iso3: "SLE", currency_code: "SLL", currency_name: "Sierra Leonean leone", currency_symbol: "Le" },
    { name: "Singapore", iso2: "SG", iso3: "SGP", currency_code: "SGD", currency_name: "Singapore dollar", currency_symbol: "$" },
    { name: "Sint Maarten", iso2: "SX", iso3: "SXM", currency_code: "ANG", currency_name: "Netherlands Antillean guilder", currency_symbol: "ƒ" },
    { name: "Slovakia", iso2: "SK", iso3: "SVK", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Slovenia", iso2: "SI", iso3: "SVN", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Solomon Islands", iso2: "SB", iso3: "SLB", currency_code: "SBD", currency_name: "Solomon Islands dollar", currency_symbol: "$" },
    { name: "Somalia", iso2: "SO", iso3: "SOM", currency_code: "SOS", currency_name: "Somali shilling", currency_symbol: "Sh" },
    { name: "South Africa", iso2: "ZA", iso3: "ZAF", currency_code: "ZAR", currency_name: "South African rand", currency_symbol: "R" },
    { name: "Spain", iso2: "ES", iso3: "ESP", currency_code: "EUR", currency_name: "Euro", currency_symbol: "€" },
    { name: "Sri Lanka", iso2: "LK", iso3: "LKA", currency_code: "LKR", currency_name: "Sri Lankan rupee", currency_symbol: "Rs" },
    { name: "Sudan", iso2: "SD", iso3: "SDN", currency_code: "SDG", currency_name: "Sudanese pound", currency_symbol: "ج.س." },
    { name: "Suriname", iso2: "SR", iso3: "SUR", currency_code: "SRD", currency_name: "Surinamese dollar", currency_symbol: "$" },
    { name: "Swaziland", iso2: "SZ", iso3: "SWZ", currency_code: "SZL", currency_name: "Swazi lilangeni", currency_symbol: "L" },
    { name: "Sweden", iso2: "SE", iso3: "SWE", currency_code: "SEK", currency_name: "Swedish krona", currency_symbol: "kr" },
    { name: "Switzerland", iso2: "CH", iso3: "CHE", currency_code: "CHF", currency_name: "Swiss franc", currency_symbol: "Fr" },
    { name: "Syria", iso2: "SY", iso3: "SYR", currency_code: "SYP", currency_name: "Syrian pound", currency_symbol: "£" },
    { name: "Taiwan", iso2: "TW", iso3: "TWN", currency_code: "TWD", currency_name: "New Taiwan dollar", currency_symbol: "$" },
    { name: "Tajikistan", iso2: "TJ", iso3: "TJK", currency_code: "TJS", currency_name: "Tajikistani somoni", currency_symbol: "ЅМ" },
    { name: "Tanzania", iso2: "TZ", iso3: "TZA", currency_code: "TZS", currency_name: "Tanzanian shilling", currency_symbol: "Sh" },
    { name: "Thailand", iso2: "TH", iso3: "THA", currency_code: "THB", currency_name: "Thai baht", currency_symbol: "฿" },
    { name: "Timor-Leste", iso2: "TL", iso3: "TLS", currency_code: "USD", currency_name: "US Dollar", currency_symbol: "$" },
    { name: "Togo", iso2: "TG", iso3: "TGO", currency_code: "XOF", currency_name: "West African CFA franc", currency_symbol: "Fr" },
    { name: "Tokelau", iso2: "TK", iso3: "TKL", currency_code: "NZD", currency_name: "New Zealand dollar", currency_symbol: "$" },
    { name: "Tonga", iso2: "TO", iso3: "TON", currency_code: "TOP", currency_name: "Tongan paʻanga", currency_symbol: "T$" },
    { name: "Trinidad and Tobago", iso2: "TT", iso3: "TTO", currency_code: "TTD", currency_name: "Trinidad and Tobago dollar", currency_symbol: "$" },
    { name: "Tunisia", iso2: "TN", iso3: "TUN", currency_code: "TND", currency_name: "Tunisian dinar", currency_symbol: "د.ت" },
    { name: "Turkey", iso2: "TR", iso3: "TUR", currency_code: "TRY", currency_name: "Turkish lira", currency_symbol: "₺" },
    { name: "Turkmenistan", iso2: "TM", iso3: "TKM", currency_code: "TMT", currency_name: "Turkmenistan manat", currency_symbol: "m" },
    { name: "Turks and Caicos Islands", iso2: "TC", iso3: "TCA", currency_code: "USD", currency_name: "US Dollar", currency_symbol: "$" },
    { name: "Tuvalu", iso2: "TV", iso3: "TUV", currency_code: "AUD", currency_name: "Australian dollar", currency_symbol: "$" },
    { name: "Uganda", iso2: "UG", iso3: "UGA", currency_code: "UGX", currency_name: "Ugandan shilling", currency_symbol: "Sh" },
    { name: "Ukraine", iso2: "UA", iso3: "UKR", currency_code: "UAH", currency_name: "Ukrainian hryvnia", currency_symbol: "₴" },
    { name: "United Arab Emirates", iso2: "AE", iso3: "ARE", currency_code: "AED", currency_name: "United Arab Emirates dirham", currency_symbol: "د.إ" },
    { name: "United Kingdom", iso2: "GB", iso3: "GBR", currency_code: "GBP", currency_name: "British pound", currency_symbol: "£" },
    { name: "United States", iso2: "US", iso3: "USA", currency_code: "USD", currency_name: "US Dollar", currency_symbol: "$" },
    { name: "Uruguay", iso2: "UY", iso3: "URY", currency_code: "UYU", currency_name: "Uruguayan peso", currency_symbol: "$" },
    { name: "Uzbekistan", iso2: "UZ", iso3: "UZB", currency_code: "UZS", currency_name: "Uzbekistani soʻm", currency_symbol: "so'm" },
    { name: "Vanuatu", iso2: "VU", iso3: "VUT", currency_code: "VUV", currency_name: "Vanuatu vatu", currency_symbol: "Vt" },
    { name: "Venezuela", iso2: "VE", iso3: "VEN", currency_code: "VEF", currency_name: "Venezuelan bolívar", currency_symbol: "Bs F" },
    { name: "Vietnam", iso2: "VN", iso3: "VNM", currency_code: "VND", currency_name: "Vietnamese đồng", currency_symbol: "₫" },
    { name: "Virgin Islands, British", iso2: "VG", iso3: "VGB", currency_code: "USD", currency_name: "US Dollar", currency_symbol: "$" },
    { name: "Virgin Islands, U.S.", iso2: "VI", iso3: "VIR", currency_code: "USD", currency_name: "US Dollar", currency_symbol: "$" },
    { name: "Wallis and Futuna", iso2: "WF", iso3: "WLF", currency_code: "XPF", currency_name: "CFP franc", currency_symbol: "Fr" },
    { name: "Yemen", iso2: "YE", iso3: "YEM", currency_code: "YER", currency_name: "Yemeni rial", currency_symbol: "﷼" },
    { name: "Zambia", iso2: "ZM", iso3: "ZMB", currency_code: "ZMW", currency_name: "Zambian kwacha", currency_symbol: "ZK" },
    { name: "Zimbabwe", iso2: "ZW", iso3: "ZWE", currency_code: "ZWL", currency_name: "Zimbabwean dollar", currency_symbol: "$" }
]
